# Generated by Django 4.2.10 on 2024-03-12 00:29

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OAuthAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300, verbose_name='OAuth Access')),
                ('expires_at', models.DateTimeField(verbose_name='Годен до')),
                ('scope', models.CharField(max_length=100, verbose_name='Scope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Для пользователя')),
            ],
            options={
                'verbose_name': 'OAuth Access Токен',
                'verbose_name_plural': 'OAuth Access Токены',
            },
        ),
        migrations.CreateModel(
            name='OAuthRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300, verbose_name='OAuth Refresh')),
                ('revoked', models.BooleanField(default=False)),
                ('access_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh', to='accounts.oauthaccesstoken', verbose_name='Access')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Для пользователя')),
            ],
            options={
                'verbose_name': 'OAuth Refresh Токен',
                'verbose_name_plural': 'OAuth Refresh Токены',
            },
        ),
    ]
